grails:
  profile: @grails.profile@
  codegen:
    defaultPackage: @grails.codegen.defaultPackage@
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
  groovy:
    template:
      check-template-location: false
